### ISSUE TITLE
Incorrect definition of associativity

### ISSUE THREAD

**Issue by dm-kovalev** [stavalfi/lectures#1]
Hi

https://github.com/stavalfi/lectures/blob/6ed87d71c2f162bb3c2b27ae13b12092d0719e16/Java%20streams%20-%20Part%204%20-%20Reduction.md#L24

You provide a definition of the _commutative_ property 

`a op b = b op a`, 

not _associative_ 

`a op (b op c) = (a op b) op c`

**Comment by stavalfi** [comment]
@dm-kovalev Thank you for noticing!

After fixing it, I also referred to the definition of associativity when explaining how `reduce`'s parallel execution works.

**Comment by dm-kovalev** [comment]
@stavalfi Thanks for the helpful tutorial :)

**Comment by ezriYerushalmi** [comment]
very good tutorial. 
thank you very much!
